### ISSUE TITLE
Update and maybe auto update ?

### ISSUE THREAD

**Issue by BuonOmo** [kowal/ruby-changelog#1]
Hey,

I've tried updating the content by running every tasks, but it did not give me much: https://github.com/BuonOmo/ruby-changelog

Are you aware of a change that may make this codebase not working anymore?

Also, don't you think it would be a great idea to have some kind of monthly autoupdate of this site ? I could work on that bit

**Comment by kowal** [comment]
hi @BuonOmo, thank you for your comment and really sorry for not replying back then 🙈 I didn't spend much time on the project in `22..

Few things have changed since then. I updated [README with current rake tasks](https://github.com/kowal/ruby-changelog#new-ruby-version):

```sh
rake fetch:cve
rake doc readme
```

The idea with auto-update is not so simple, because I really want to pick the most important changes by hand. When I was starting this project it was also meant to be an occasion for me to stay up to date with Ruby latest features 😅

**Comment by kowal** [comment]
Worth mentioning - since then I've also added a timeline page - https://rubychangelog.com/timeline

**Comment by BuonOmo** [comment]
Got you, closing then thank you !
